### PR TITLE
adding rate limiter

### PR DESCRIPTION
**Pull request by ProgrammerDan**
This should layer in to the other open PRs, it's not complete.

Significant rewrite of this local, but putting this placeholder here so there is visibility as development is active-ish.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
@Maxopoly @ribagi  Thoughts on this improved approach? I think I finished out the base coding last night, then I'll do testing tonight.

Let me know if you see obvious deficiencies / problems. All config driven, example is in config.yml and is "empty-safe" (everything is just turned off) so there's no issue if someone upgrades to this release but doesn't update their config.

**Comment by ProgrammerDan** [comment]
Got a chance to test it, seems to work really well. Any thoughts or concerns from review @Maxopoly  @ribagi anyone else?

**Comment by ProgrammerDan** [comment]
Last call, gonna start mergemashing tonight so that this isn't a blocker any longer

**Comment by Maxopoly** [comment]
Integrating it into the GUI would probably be good, people use the GUI more than commands by now and automating spamming through it is just as easy with MacroMod

**Comment by ProgrammerDan** [comment]
ah was under mistaken assumption that the GUI didn't have same impact, assumed you had done some kind of baked in magic :P.

Yeah, can do

**Comment by ProgrammerDan** [comment]
@Maxopoly haven't run tests but builds -- what do you think of changes?

**Pull request closed without merging**
